version: '3.7'

services: 
  db:
    image: postgres:12
    volumes: 
      - pg_data:/var/lib/postgresql/data/
    environment: 
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB : postgres
  django:
    container_name: menu_app_web
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/online_menu/manage.py migrate --noinput &&
             python /usr/src/online_menu/manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/usr/src/online_menu

    ports: 
      - 8000:8000

    depends_on: 
      - db
volumes: 
  pg_data: